site_name: Docs Test 250829
docs_dir: docs
theme:
  name: readthedocs

nav:
  - Table of Contents: index.md
  - Chapter 1: chapter1/chapter1.md
  - Chapter 2: chapter2/chapter2.md
  - Chapter 3: chapter3/chapter3.md